// Every string in Hive, keyed, in the two languages it is written in.
//
// The app is written in Mexican Spanish and translated into English, so ES is
// the table that has to be complete: `t` falls back to it by construction, and
// a key missing from EN shows Spanish, which is visible and fixable, rather
// than a key name, which looks like a crash.
//
// Three rules, each of which cost a bug to learn.
//
// Whole sentences live here, not fragments. Spanish reorders them ("Le debes
// $9.50 a Rocío"), so a sentence assembled from translated pieces is always
// wrong in one language or the other. Where a sentence has a value in it, it
// is a `{slot}` and `tf` fills it.
//
// Copy is read at render, never at module load. These are plain data; the
// reading happens through `t(lang, key)` or the `useT()` hook, so nothing
// freezes whichever language rendered first.
//
// And the fallback is whole-language: a phone set to Italian gets English, not
// an Italian shell with Spanish rows in it.
//
// Length is the thing to watch. Spanish runs 15 to 25 percent longer than
// English, so English is the easy direction and Spanish is the one that
// overflows. The tab bar is the canary: five labels, fixed width, no wrap.

export const ES = {
  // -- chrome ---------------------------------------------------------------
  'tab.clubs': 'Clubes',
  'tab.events': 'Eventos',
  'tab.home': 'Inicio',
  'tab.plate': 'Pendientes',
  'tab.you': 'Tú',

  'common.save': 'Guardar',
  'common.cancel': 'Cancelar',
  'common.saving': 'Guardando…',
  'common.saved': 'Listo',
  'common.remove': 'Quitar',
  'common.delete': 'Eliminar',
  'common.edit': 'Editar',
  'common.add': 'Agregar',
  'common.close': 'Cerrar',
  'common.back': 'Volver',
  'common.confirm': 'Confirmar',
  'common.continue': 'Continuar',
  'common.copy': 'Copiar',
  'common.copied': 'Copiado',
  'common.seeAll': 'Ver todo',
  'common.optional': 'Opcional',
  'common.none': 'Ninguno',
  'common.search': 'Busca eventos, clubes, personas',
  'common.retry': 'Intenta de nuevo.',

  // -- home -----------------------------------------------------------------
  'home.greeting': 'hola, {name}',
  'home.plate': 'En tu plato',
  'home.plate.more': '+{n} más',
  'home.upcoming': 'Lo que viene',
  'home.upcoming.empty': 'Nada en puerta todavía.',
  'home.history': 'Tu historial',
  'home.clubs': 'Tus clubes',
  'home.clubs.empty.title': 'Todavía no estás en ningún club',
  'home.clubs.empty.hint': 'Pide a quien organiza que te invite, o empieza el tuyo.',
  'home.away': 'Mientras no estabas',
  'home.plate.clear': 'Todo en orden. Nada te necesita ahorita.',
  'home.clubs.empty.short': 'Pide a quien organiza que te invite.',
  'home.createClub': 'Crear club',

  // -- clubs ----------------------------------------------------------------
  'clubs.title': 'Clubes',
  'clubs.quiet': 'Sin nada planeado',
  'clubs.quietSince': 'Tranquilo desde {month}.',
  'clubs.newEvent': 'Nuevo evento',
  'clubs.empty.title': 'Todavía no estás en ningún club',
  'clubs.empty.hint': 'Pide a quien organiza que te invite, o empieza el tuyo.',

  // -- events ---------------------------------------------------------------
  'events.title': 'Eventos',
  'events.lede': 'Todo lo que han hecho tus clubes.',
  'events.filters': 'Filtros',
  'events.filter.club': 'Club',
  'events.filter.cat': 'Categoría',
  'events.filter.person': 'Quién fue',
  'events.filter.when': 'Cuándo',
  'events.filter.place': 'Lugar',
  'events.filter.sort': 'Ordenar',
  'events.filter.money': 'Dinero',
  'events.filter.all': 'Todos',
  'events.filter.allF': 'Todas',
  'events.filter.anyone': 'Cualquiera',
  'events.filter.anyDate': 'Cualquier fecha',
  'events.filter.upcoming': 'Próximos',
  'events.filter.past': 'Pasados',
  'events.filter.newest': 'Más recientes',
  'events.filter.oldest': 'Más antiguos',
  'events.filter.mostOwed': 'Más se debe',
  'events.filter.owedOnly': 'Solo con dinero pendiente',
  'events.filter.you': 'Tú',
  'events.filter.clear': 'Quitar filtro {label}',
  'events.count': '{n} eventos',
  'events.count.one': '1 evento',
  'events.owed.total': 'pendiente en total',
  'events.owed.you': 'todavía debes',
  'events.owed.person': '{name} todavía debe',
  'events.empty.title': 'No hay eventos que coincidan.',
  'events.empty.hint': 'Afloja algún filtro.',
  'events.noPlace': 'sin lugar',
  'events.went': '{n} fueron',
  'events.noCategory': 'sin categoría',

  // -- when -----------------------------------------------------------------
  'when.finding': 'Buscando fecha',
  'when.today': 'Hoy',
  'when.tomorrow': 'Mañana',

  // -- account --------------------------------------------------------------
  'account.title': 'Mi cuenta',
  'account.lede': 'Tu bicho, cómo entras, cómo te avisamos y cómo te pagan.',
  'account.group.you': 'Tú',
  'account.group.signin': 'Cómo entras',
  'account.group.notify': 'Cómo te avisa Hive',
  'account.group.money': 'Cómo te pagan',
  'account.group.places': 'Lugares donde puedes recibir',
  'account.group.platform': 'Plataforma',
  'account.signin.note': 'Entras con un enlace a tu correo o con un código por WhatsApp. No hay contraseñas.',
  'account.email': 'Correo',
  'account.email.none': 'sin correo',
  'account.verified': 'verificado',
  'account.name': 'Nombre visible',
  'account.photo': 'O usa tu propia foto',
  'account.photo.change': 'Cambiar foto',
  'account.photo.back': 'Volver a tu bicho',
  'account.photo.failed': 'No se pudo subir la foto. Intenta de nuevo.',
  'account.bug.hint': 'Elige un bicho y un color para que el club te distinga a simple vista.',
  'account.photo.hint': 'Tu foto se muestra en vez de tu bicho, con el mismo recorte hexagonal.',
  'account.crop.title': 'Encuadra tu foto',

  'lang.label': 'Idioma',
  'lang.auto': 'Sigue tu teléfono',
  'lang.es': 'Español',
  'lang.en': 'English',

  'platform.door': 'Panel de administración',
  'platform.meta': 'cuentas y entregas',

  'danger.zone': 'Zona de riesgo',
  'danger.signout': 'Cerrar sesión',
  'danger.delete': 'Eliminar cuenta',
  'danger.note': 'Tu asistencia y gastos pasados se quedan en el historial de los clubes; tu perfil y tu forma de entrar se eliminan.',

  // -- notifications --------------------------------------------------------
  'notif.email': 'Correo',
  'notif.whatsapp': 'WhatsApp',
  'notif.push': 'Avisos',
  'notif.scope.you': 'tú',
  'notif.scope.device': 'este dispositivo',
  'notif.needWhatsapp': 'Agrega tu número de WhatsApp arriba para encender esa columna.',
  'notif.kept': 'Lo que elijas aquí se guarda y empieza a aplicar en cuanto se encienda.',
  'notif.topic.new_event': 'Nuevos eventos en mis clubs',
  'notif.topic.reminders': 'Recordatorio el día del evento',
  'notif.topic.rsvp_waitlist': 'RSVP y lista de espera',
  'notif.topic.payments': 'Pagos (me pagaron o confirmaron)',
  'notif.topic.approvals': 'Decisiones de admins (cambios y solicitudes)',

  'push.off': 'Los avisos están apagados en este dispositivo.',
  'push.denied': 'Este navegador está bloqueando los avisos en este dispositivo.',
  'push.install': 'En iPhone hay que agregar Hive a la pantalla de inicio antes de poder activar los avisos.',
  'push.unsupported': 'Este navegador no puede mostrar avisos.',

  // -- plate ----------------------------------------------------------------
  'plate.title': 'Pendientes',
  'plate.pay': 'Pagos · por hacer',
  'plate.pay.oldest': 'más viejo primero',
  'plate.owedToYou': 'Te deben',
  'plate.awaiting': 'Esperan tu confirmación',
  'plate.empty.title': 'Nada pendiente',
  'plate.empty.hint': 'Cuando alguien te deba algo o falte tu respuesta, aparece aquí.',
  'plate.owe': 'Le debes {amount} a {name}',
  'plate.paidYou': '{name} dice que te pagó {amount}',
  'plate.rsvp': '¿Vas a ir?',
  'plate.availability': 'Marca cuándo puedes',
  'plate.vote': 'Falta tu voto',
  'plate.later': 'Todavía no',
  'plate.payTo': 'Pagar a {name}',
  'plate.lede': 'Todo lo pendiente antes de que cierre cada evento. Actúa aquí, o toca el nombre del evento para abrirlo.',
  'plate.clear.title': 'Todo en orden.',
  'plate.clear.hint': 'No tienes nada pendiente por ahora. A disfrutar el zumbido.',
  'plate.waiting': 'Te están esperando',
  'plate.tasks': 'Tareas',
  'plate.bringing': 'Traes',
  'plate.put': '{name} puso {amount}',

  // -- event ----------------------------------------------------------------
  'event.going': 'Quién va',
  'event.contributions': 'Aportaciones',
  'event.polls': 'Encuestas',
  'event.money': 'Dinero',
  'event.photos': 'Fotos',
  'event.thread': 'Conversación',
  'event.elsewhere': 'En otra parte',
  'event.details': 'Detalles, organizadores, calendario',
  'event.noPlaceYet': 'Sin lugar todavía',
  'event.setPlace': 'Poner un lugar',
  'event.changePlace': 'Cambiar lugar',
  'event.directions': 'Cómo llegar',
  'event.rsvp.ask': '¿Vas a ir?',
  'event.rsvp.going': 'Voy',
  'event.rsvp.maybe': 'Quizás',
  'event.rsvp.no': 'No voy',
  'event.rsvp.change': 'cambiar',
  'event.cancelled': 'cancelado',
  'event.waitlisted': 'en espera',
  'event.youGo': 'vas',
  'event.youWent': 'fuiste',
  'event.guestName': 'Nombre de quien traes',
  'event.bringSomeone': 'Traer a alguien (+1)',
  'event.noRoomGuests': 'Ya no hay lugar para traer a alguien más.',
  'event.waitlist.note': 'Cuando se libera una plaza, el primero en la fila entra solo y le avisamos por correo y WhatsApp.',
  'event.sheet': 'Ficha',
  'event.closed': 'Los RSVPs y la lista de aportaciones ya están cerrados. Lo demás se queda como historial.',
  'event.contrib.empty': 'Nadie trae nada todavía. Estrena la lista.',
  'event.organizers': 'Organizadores',
  'event.stillFinding': 'Seguimos buscando fecha. Marca cuándo puedes abajo.',
  'event.markAvailability': 'Falta que marques cuándo puedes',
  'event.otherEvents': 'Otros eventos de este club',
  'event.undo': 'deshacer',
  'event.done': 'hecho',
  'event.host': 'host',
  'event.pending': 'pendiente',
  'event.task': 'tarea',
  'event.dontForget': 'no se te olvide',

  // -- create / edit event --------------------------------------------------
  'form.title': 'Título',
  'form.title.ph': 'Noche de juegos',
  'form.title.missing': 'Dale un título primero.',
  'form.category': 'Categoría',
  'form.category.none': 'Sin categoría',
  'form.category.name': 'Nombre de la categoría',
  'form.category.ph': 'Cata de vinos',
  'form.place': 'Lugar (opcional)',
  'form.findDate': 'Buscar fecha',
  'form.window': 'La ventana de fechas y horas donde los miembros marcan cuándo pueden.',
  'form.from': 'Desde',
  'form.to': 'Hasta',
  'form.timeFrom': 'De',
  'form.timeTo': 'A',
  'form.cells': 'Celdas',
  'form.grain': 'Qué tan fino se marca',
  'form.extras': 'Agrega si lo necesitas',
  'form.cap.offer': 'Un límite de cuántos caben',
  'form.cap.consequence': 'Con lista de espera cuando se llene',
  'form.cap.label': 'Cupo',
  'form.cap.max': 'Cupo máx.',
  'form.waitlist': 'lista de espera',
  'form.cap.hint': 'Sin cupo el evento nunca se llena, y nadie espera.',
  'form.guests.offer': 'Que traigan a alguien',
  'form.guests.consequence': 'Una pareja, un par de amigos',
  'form.guests.each': 'cada miembro puede traer',
  'form.guests.less': 'uno menos',
  'form.guests.more': 'uno más',
  'form.guests.hint': 'Cada invitado ocupa un lugar del cupo, igual que un miembro.',
  'form.deadline.offer': 'Una fecha para confirmar',
  'form.deadline.consequence': 'A quien no haya contestado le llega un recordatorio',
  'form.deadline.label': 'Confirmar antes de',
  'form.join': 'Quién puede entrar con el enlace',
  'form.join.members': 'solo miembros del club',
  'form.join.link': 'cualquiera con el enlace',
  'form.join.invite': 'solo con invitación',
  'form.create': 'Crear evento',
  'form.createAndAsk': 'Crear y pedir horarios',
  'form.extras.hint': 'La mayoría de los eventos no necesitan ninguna. La lista de lo que hay que traer y las encuestas se agregan en el evento, una vez que existe y la gente ya puede apartar cosas.',
  'form.saveChanges': 'Guardar cambios',

  // -- club page ------------------------------------------------------------
  'club.notMember': 'Este club no existe o todavía no eres miembro. Pide el enlace de invitación.',
  'club.the': 'El club',
  'club.members': 'Miembros',
  'club.subscribe': 'Suscribirme',
  'club.pastEvents': 'Eventos pasados',
  'club.removeMember': 'Quitar miembro',
  'club.approve': 'Aprobar',
  'club.decline': 'Rechazar',
  'club.emptyCategory': 'Nada en esta categoría todavía.',
  'club.allCategories': 'Todos',

  // -- push row -------------------------------------------------------------
  'push.title': 'Avisos',
  'push.enable': 'Activar',
  'push.on': 'activado',
  'push.blocked': 'bloqueado',
  'push.unsupported.title': 'Este navegador no admite avisos',
  'push.alsoOn': 'También activado en',
  'push.what': 'Un aviso en la pantalla cuando pasa algo, sin abrir la app. Solo en este navegador.',
  'push.working': 'Los avisos llegan a este navegador. Es por dispositivo: en tu otro teléfono hay que activarlos aparte.',
  'push.blocked.help': 'Este navegador los tiene bloqueados. Sigue los pasos de abajo para desbloquearlos.',
  'push.step1': '1. Toca el candado o los tres puntos junto a la dirección.',
  'push.step2': '2. Busca Notificaciones y cámbialo a Permitir.',
  'push.step3': '3. Vuelve aquí y recarga la página.',
  'push.unsupported.note': 'Este navegador no admite avisos. Te seguimos avisando por correo y WhatsApp.',

  // -- money ----------------------------------------------------------------
  'money.amount': 'Cantidad',
  'money.method': 'Método',
  'money.to': 'Para',
  'money.receipt': 'Comprobante de pago',
  'money.receipt.upload': 'Toca para subir una captura de la transferencia',
  'money.receipt.private': 'Solo tú puedes ver esto, porque eres quien lo recibió.',
  'money.how': '¿Cómo pagaste?',
  'money.pay': 'Pagar',
  'money.confirm': 'Confirmar',
  'money.confirmPayment': 'Confirmar pago',
  'money.confirmReceived': 'Confirmar recibido',
  'club.creating': 'Creando…',
  'money.expense.add': 'Añadir un gasto',
  'money.expense.edit': 'Editar gasto',
  'money.expense.what': 'Qué fue',
  'money.expense.split': 'Entre quiénes se reparte',
  'money.expense.youPaid': 'Lo pagaste tú',
  'money.expense.settled': 'Los pagos ya confirmados se quedan como están',

  // -- contributions --------------------------------------------------------
  'contrib.add': 'Añadir aportación',
  'contrib.edit': 'Editar aportación',
  'contrib.what': 'Qué',
  'contrib.type': 'Tipo',
  'contrib.forWhom': 'Para quién',
  'contrib.qty': 'Cantidad (opcional)',
  'contrib.qty.ph': 'cantidad',
  'contrib.bring': 'traer algo',
  'contrib.task': 'tarea',
  'contrib.forMe': 'para mí',
  'contrib.open': 'abierto (que alguien se lo pida)',
  'contrib.onlyYou': 'Te lo apuntas tú. Asignarle algo a alguien más lo hace quien organiza.',


  // -- roles ----------------------------------------------------------------
  'role.admin': 'admin',
  'role.organizer': 'organizador',
  'role.member': 'miembro',
  'role.guest': 'invitado',

  // -- club admin -----------------------------------------------------------
  'club.about.edit': 'Editar acerca de',
  'club.about.desc': 'Descripción',
  'club.about.links': 'Enlaces',
  'club.about.removeLink': 'Quitar enlace',
  'club.about.linkLabel': 'Etiqueta',
  'club.about.linkUrl': 'link.com/…',
  'club.avatar.change': 'Cambiar foto del club',
  'club.avatar.crop': 'Encuadra la foto del club',
  'club.banner.change': 'Cambiar portada',
  'club.banner.crop': 'Encuadra la portada',
  'club.cal.regen': '¿Cambiar el enlace del calendario?',
  'club.cal.regen.warn': 'Quien ya se suscribió tendrá que agregarlo otra vez',
  'club.cat': 'Categoría',
  'club.cat.edit': 'Editar categoría',
  'club.cat.name': 'Nombre de la categoría',
  'club.cat.ph': 'Juegos de mesa',
  'club.cat.emoji': 'Emoji',
  'club.leave.warn': 'Sales del roster y dejas de ver los eventos de este club. Tu historial se queda intacto.',
  'club.irreversible': 'Esto no se puede deshacer',
  'club.gotIt': 'Entendido',
  'club.invite.email': 'Correo',
  'club.invite.whatsapp': 'O WhatsApp',
  'club.invite.role': 'Rol',
  'club.invite.auto': 'Si dejas un correo, la invitación se manda sola',
  'club.joinLink': 'Enlace para unirse',
  'club.revoke': 'Revocar',
  'club.join.anyone': 'cualquiera con el enlace (pide aprobación)',
  'club.join.invite': 'solo con invitación',
  'club.join.no': 'no puede',
  'club.new': 'Nuevo club',
  'club.create': 'Crear club',
  'club.name': 'Nombre del club',
  'club.name.ph': 'Los Jueves',
  'club.create.modal': 'Crear un club',
  'club.create.firstAdmin': 'Vas a ser su primer admin',
  'club.create.next': 'Después: invita gente y crea tu primer evento.',
  'club.notFound': 'Club no encontrado',
  'club.private': 'Club privado',
  'club.joinTo': 'Únete a',
  'club.notMemberShort': 'Este club no existe o no eres miembro.',
  'club.newEvent.title': 'Nuevo evento',

  // -- account extras -------------------------------------------------------
  'account.profile': 'Perfil',
  'account.yourBug': 'Tu bicho',
  'account.delete.confirm': '¿Eliminar tu cuenta?',
  'account.delete.type': 'Escribe DELETE para confirmar',
  'account.irreversible': 'Esto no se puede deshacer',
  'account.pay.remove': 'Quitar forma de pago',
  'account.pay.ph': 'Número, alias, nota…',
  'account.place.name': 'Nombre',
  'account.place.addr': 'Dirección',
  'account.place.ph': 'Casa de Marta',
  'account.place.missing': 'Faltan el nombre y la dirección.',
  'account.place.noPin': 'Sin pin. El mapa lo busca por la dirección.',
  'account.place.yours': 'tus lugares',
  'account.wa.number': 'Número de WhatsApp',
  'account.wa.ph': '+52 55 1234 5678',
  'account.wa.change': 'Cambiar número',
  'account.wa.remove': '¿Quitar tu WhatsApp?',

  // -- event extras ---------------------------------------------------------
  'event.rollcall.who': '¿Quién vino?',
  'event.rollcall.tap': 'Toca a quien no llegó.',
  'event.rollcall.private': 'No le llega a nadie. Puedes corregirla después.',
  'event.rollcall.absent': 'no vino',
  'event.claim.ask': '¿Lo traes tú?',
  'event.coorg.add': 'Añadir co-organizador',
  'event.coorg.can': 'Puede editar el evento y gestionar quién va',
  'event.coorg.none': 'No hay más miembros del club para invitar.',
  'event.coorg.note': 'Solo organizadores y admins del club pueden co-organizar. La invitación se avisa por correo y WhatsApp.',
  'event.coorg.invite': 'Invitar',
  'event.again': '¿Otra vez?',
  'event.notNow': 'Ahora no',
  'event.dup': 'Duplicar',
  'event.dup.title': 'Duplicar este evento',
  'event.dup.newDate': 'Fecha nueva',
  'event.dup.week': '¿En qué semana la busca?',
  'event.dup.fresh': 'Empieza de cero',
  'event.dup.kept': 'Se mantiene',
  'event.dup.hint': 'Nadie está apuntado y nada está apartado todavía. Es lo normal en una noche nueva, no es que se haya salido todo el mundo.',
  'event.edit': 'Editar evento',
  'event.settle': 'Liquidar',
  'event.toConfirm': 'Pagos por confirmar',
  'event.noExpenses': 'Sin gastos todavía.',
  'event.byHand': 'a mano',
  'event.withdraw': 'retirar',
  'event.bestSlots': 'Mejores huecos',
  'event.remembered': 'recordado',

  // -- admin ----------------------------------------------------------------
  'admin.title': 'Admin',
  'admin.none': 'Nadie espera a que le verifiquen la cuenta.',
  'admin.verify': 'Verificar',
  'admin.disable': 'desactivar',
  'admin.reactivate': 'reactivar',
  'admin.users': 'Usuarios',
  'admin.delivery': 'Envíos',
  'admin.templates': 'Plantillas',
  'admin.outbox.empty': 'Todavía no sale ningún mensaje.',
  'admin.tpl.subject': 'Asunto',
  'admin.tpl.noWa': 'sin enviar a WhatsApp',


  // -- invitations ----------------------------------------------------------
  'inv.link': 'Enlace del evento',
  'inv.who': 'Quién puede entrar con él',
  'inv.personal': 'Invitación personal',
  'inv.none': 'Todavía no invitas a nadie',
  'inv.none.hint': 'Comparte el enlace del evento o manda una invitación personal.',
  'inv.email.ph': 'correo',
  'inv.wa.ph': 'o WhatsApp (+52 …)',
  'inv.accepted': 'aceptada',
  'inv.pending': 'pendiente',
  'inv.expired': 'venció',
  'inv.anyone': 'Cualquiera con el enlace',
  'inv.inviteOnly': 'Solo con invitación',
  'inv.membersOnly': 'Solo miembros del club',
  'inv.no': 'no puede',
  'inv.youWere': 'Te invitaron',
  'inv.used': 'Esta invitación ya se usó',
  'inv.tooLate': 'Esta invitación ya venció',
  'inv.noted': 'Quedamos avisados',
  'inv.alreadyIn': 'Ya estás dentro',
  'inv.yourEmail': 'Tu correo',
  'inv.email.example': 'tu@correo.com',

  // -- place picker ---------------------------------------------------------
  'place.ph': 'Casa de… o una dirección',
  'place.yours': 'Tus lugares',
  'place.recent': 'Recientes',
  'place.drag': 'Arrastra el pin o toca el mapa para moverlo. Aquí es a donde llega quien venga.',
  'place.tapMap': 'Toca el mapa para poner el pin exacto.',
  'place.searching': 'Buscando la dirección…',

  // -- polls ----------------------------------------------------------------
  'poll.empty': 'Nadie ha preguntado nada todavía.',
  'poll.hidden': 'Los resultados se ven cuando cierre la encuesta.',
  'poll.visible': 'El voto sigue a la vista aunque se haya elegido una opción.',
  'poll.closed': 'cerrada',
  'poll.pick': 'elegir',

  // -- misc -----------------------------------------------------------------
  'pwa.title': 'Ten Hive a la mano',
  'pwa.hide': 'Ocultar',
  'thread.ph': 'Escribe algo para el grupo…',
  'thread.send': 'Enviar',
  'thread.delete': 'Borrar',
  'signin.ph': 'tu@correo.com  ·  55 1234 5678',


  // -- sign in flow ---------------------------------------------------------
  'signin.linkUsed': 'Ese enlace ya se usó o ya venció. Cada enlace sirve una sola vez (a veces tu correo lo abre antes que tú). Pide uno nuevo.',
  'signin.tooMany': 'Muchos intentos seguidos. Espera un minuto y vuelve a pedir el enlace.',
  'signin.sendFailed': 'No pudimos completar el envío. Revisa tu conexión e intenta de nuevo.',
  'signin.checkEmail': 'Revisa tu correo',
  'signin.changeNumber': 'Cambiar número',
  'signin.noAccountPhone': 'Si ese número no tiene cuenta en Hive, no llegará nada. Prueba con tu correo.',
  'signin.noAccountEmail': 'Si ese correo no tiene cuenta en Hive, no llegará nada. Prueba con tu WhatsApp.',

  // -- invite ---------------------------------------------------------------
  'invite.findingDate': 'Todavía están buscando fecha entre todos.',
  'invite.noPlace': 'Falta definir el lugar.',
  'invite.nobodyYet': 'Nadie ha confirmado todavía',
  'invite.accept?': '¿Aceptas la invitación?',
  'invite.accept': 'Aceptar invitación',
  'invite.saidNo': 'Ya dijiste que no puedes. Deshacer',
  'invite.changedMind': 'Cambié de opinión, sí voy',
  'invite.noForms': 'Sin contraseñas, sin formularios.',

  // -- plate loud -----------------------------------------------------------
  'plate.markWhen': 'Marca cuándo puedes',
  'plate.needsAll': 'Nadie puede fijar la fecha hasta que respondan todos.',
  'plate.rsvpWhy': 'Saber quién va decide el lugar y lo que hay que llevar.',
  'plate.alsoToPay': 'También por pagar',
  'plate.done!': '¡Listo!',
  'plate.taskDone': 'Tarea hecha. Una cosa menos en tu plato.',
  'plate.bringNoted': 'Apuntado como llevado. No se te olvide en la puerta.',
  'plate.markTaskDone': '¿Marcar la tarea como hecha?',
  'plate.markBrought': '¿Marcar como llevado?',
  'plate.yesDone': 'Sí, ya está',
  'plate.yesBring': 'Sí, yo lo llevo',
  'plate.taskWarn': 'Al marcarla hecha, desaparece de la lista de todos. Si te equivocas, se puede deshacer.',
  'plate.bringWarn': 'Al confirmarlo, el club lo da por cubierto. Si te equivocas, se puede deshacer.',

  // -- grid -----------------------------------------------------------------
  'grid.markMine': 'Marcar la mía',
  'grid.dragDay': 'Arrastra sobre el día para elegir el rango exacto.',
  'grid.holdDrag': 'Mantén y arrastra sobre un día. Cuanto más honey, más gente puede.',
  'grid.nothingPicked': 'Nada elegido todavía.',
  'grid.alreadyReminded': 'Ya les habíamos recordado',
  'grid.autoReminder': 'Se manda solo cuando pasa la fecha límite para confirmar. Solo llega una vez.',

  // -- sign in --------------------------------------------------------------
  'signin.checkWa': 'Revisa tu WhatsApp',
  'signin.changeEmail': 'Cambiar correo',
  'signin.checkEmailLink': 'Revisa tu correo. Te mandamos un enlace, ábrelo en este mismo navegador para volver aquí.',
  'invite.goingOne': '{n} persona va',
  'invite.goingMany': '{n} personas van',
  'invite.oneMoment': 'Un momento…',
  'invite.telling': 'Avisando…',
  'invite.cant': 'No voy a poder',

  // -- the invitation landing, whole sentences ------------------------------
  //
  // Every branch of this screen is one key. It used to be built by
  // concatenating a translated half with a Spanish half ("Ya tienes sesión
  // iniciada. Al aceptar" + " te unes a «{club}»" + " y quien organiza va a
  // ver tu nombre."), which is trap three from the design's language section
  // and the reason an English phone read half in Spanish. A sentence in
  // pieces cannot be reordered, and Spanish and English do not put the club
  // in the same place.
  'inv.notFound.hint': 'El enlace no es válido. Pide a quien organiza que te mande otro.',
  'inv.sub.eventClub.by': '{name} te invitó con «{club}».',
  'inv.sub.eventClub': 'Te invitaron con «{club}».',
  'inv.sub.by': '{name} te invitó a unirte.',
  'inv.sub': 'Te invitaron a unirte.',
  'invite.spotsOne': 'queda 1 de {capacity} de cupo',
  'invite.spotsMany': 'quedan {n} de {capacity} de cupo',
  'invite.full': 'el cupo de {capacity} ya está lleno, entrarías a la lista de espera',
  'invite.expired.by': 'Los enlaces duran 30 días. Pídele otro a {name} y entras sin problema.',
  'invite.expired': 'Los enlaces duran 30 días. Pide otro a quien te invitó y entras sin problema.',
  'inv.alreadyIn.club': 'Usaste esta invitación y ya eres parte de «{club}».',
  'inv.alreadyIn.hint': 'Usaste esta invitación.',
  'inv.goEvent': 'Ir al evento',
  'inv.goClub': 'Ir al club',
  'inv.used.by': 'Alguien más la abrió antes. Pídele otra a {name} si era para ti.',
  'inv.used.hint': 'Alguien más la abrió antes. Pide otra a quien te invitó si era para ti.',
  'inv.joinClub?': '¿Te unes a «{club}»?',
  'inv.signedIn.club':
    'Ya tienes sesión iniciada. Al aceptar te unes a «{club}» y quien organiza va a ver tu nombre.',
  'inv.signedIn.event':
    'Ya tienes sesión iniciada. Al aceptar quedas dentro y quien organiza va a ver tu nombre.',
  'invite.declined.by': '{name} va a ver que no puedes. Si cambias de opinión, este enlace sigue sirviendo.',
  'invite.declined': 'Quien te invitó va a ver que no puedes. Si cambias de opinión, este enlace sigue sirviendo.',
  // {email} is bolded by splitting the rendered sentence on the slot, so the
  // whole sentence still lives here and a translator can move the address.
  'inv.sentTo': 'Te mandamos un enlace a {email}. Ábrelo en este mismo navegador.',
  'inv.emailIntro': 'Pon tu correo y te mandamos un enlace para entrar. Sin contraseñas.',
  'inv.phoneOnly':
    'Te invitaron por WhatsApp. Por ahora se entra con correo, pon el tuyo y tu invitación queda ligada.',

  // -- the club join link ---------------------------------------------------
  'club.notFound.hint': 'El enlace no es válido. Pide a quien administra el club que te mande otro.',
  'club.private.hint': 'Este club solo se une por invitación directa. Pide a alguien miembro que te invite.',
  'club.join.sent':
    'Revisa tu correo. Te mandamos un enlace: ábrelo en este mismo navegador para volver aquí y pedir tu ingreso.',
  'club.request.intro':
    'Manda tu solicitud para unirte. Quien administra el club la revisa antes de que entres.',
  'club.request.action': 'Pedir unirme',
  'club.request.sent': 'Tu solicitud se envió. Quien administra «{club}» la va a revisar.',
  'common.sending': 'Enviando…',
  'plate.toPay': 'Pagos · por hacer',
  'money.markPaid': 'Marcar como pagado',
  'grid.fixTime': 'Fijar la hora',
  'grid.slotsMarked': '{n} huecos marcados',
  'grid.slotMarked': '{n} hueco marcado',
  'grid.savingDots': ' · guardando…',
  'grid.savedDots': ' · guardado',
  'common.notSaved': 'No se pudo guardar.',
  'common.needName': 'Necesitas un nombre visible.',
  'account.place.save': 'Guardar lugar',
  'account.thisDevice': 'este equipo',
  'push.thisBrowser': 'este navegador',
  'push.onDevice': '{browser} en {os}',
  'push.alertsIn': 'Avisos en {device}',
  'push.turningOn': 'Activando…',
  'push.turnedOn': 'Avisos activados en este dispositivo.',
  'push.turnedOff': 'Avisos apagados en este dispositivo.',
  'push.failOn': 'No se pudieron activar los avisos.',
  'push.failOff': 'No se pudieron apagar los avisos.',
  'account.wa.done': 'Listo, ya te avisamos por WhatsApp',
  'account.wa.send': 'Mandar código',
  'pending.disabled': 'Tu cuenta está desactivada',
  'pending.disabled.body': 'Por ahora no puedes entrar a tus clubes ni a los eventos. Si crees que es un error, escríbele a quien administra.',
  'pending.nudged': 'Ya les avisamos. Te toca esperar un poco.',
  'pending.nudgedToday': 'Ya les habíamos avisado hoy',
  'dup.rsvps': 'Quién va, todos vuelven a confirmar',
  'dup.availability': 'La disponibilidad, la encuesta empieza vacía',
  'dup.contribs': 'Quién trae qué, la lista pasa sin dueño',
  'dup.guests': 'Los invitados, nadie arrastra sus +1',
  'dup.failed': 'No se pudo duplicar el evento.',
  'event.noPlaceYet2': 'Sin lugar todavía',
  'event.copyFailed': 'No se pudo copiar. Mantén presionado el enlace.',
  'event.toBin': 'Va a la papelera. 30 días para recuperarlo.',
  'event.askedAdmin': 'Se lo pedimos a la administración del club',
  'event.cancelledNotice': 'Evento cancelado. Se avisó a quienes iban.',
  'event.binNoPhotos': 'Este evento está en la papelera, no se pueden agregar fotos.',
  'event.onlyWentPhotos': 'Solo quien fue al evento puede agregar fotos.',
  'event.askedToJoin': 'Ya pediste unirte. Un organizador o admin te va a dejar entrar pronto.',
  'event.guestCanRsvp': 'Puedes confirmar y aportar en este evento aunque no seas del club.',
  'event.fixedTime': 'fijó la hora',
  'event.join.anyone': 'Cualquiera con el enlace puede entrar.',
  'event.join.invite': 'Solo con invitación.',
  'event.join.members': 'Solo miembros del club.',
  'event.withWaitlist': ', con lista de espera',
  'event.noWaitlist': ', sin lista de espera',
  'poll.alive': 'La encuesta está viva.',
  'poll.ph': '¿A qué jugamos?',
  'poll.question': 'Pregunta',
  'poll.anon': 'anónima',
  'event.howPaid': 'Cómo te pagan de vuelta',
  'event.payDetails': 'Datos de pago',
  'event.myDetails': 'mis datos',
  'event.claimed': 'Apuntado. El club cuenta contigo.',
  'contrib.added': 'Añadido a aportaciones.',
  'contrib.updated': 'Aportación actualizada.',
  'contrib.whatNeeded': 'Qué hace falta',
  'contrib.whatBring': 'Qué vas a traer',
  'event.rollcall.failed': 'No se pudo guardar la lista.',
  'event.organization': 'la organización',
  'money.expense.saved': 'Gasto guardado. Se actualizó el reparto.',
  'money.expense.failed': 'No se pudo guardar el gasto.',
  'inv.resent': 'Invitación reenviada',
  'form.grain.hint': 'Se marca rápido. Suficiente para la mayoría de los planes.',
  'common.back2': 'Atrás',
  'common.more': 'Más',
  'common.notSent': 'No se pudo enviar.',
  'common.notUpdated': 'No se pudo actualizar.',
  'money.notRecorded': 'No se pudo registrar el pago.',
  'ui.emoji.hint': 'Usa el emoji de tu teclado',
  'ui.code.label': 'Código de 6 dígitos',
  'ui.code.expired': 'Ya venció. Pide uno nuevo.',
  'ui.crop.hint': 'Arrastra para mover, desliza para acercar',
  'app.description': 'Eventos de club sin caos: fecha, confirmaciones, quién trae qué, gastos.',
  'plate.snooze': 'Vuelve mañana',
  'admin.outbox.sent': 'enviado',
  'admin.outbox.waiting': 'esperando confirmación',
  'admin.outbox.queued': 'en cola',
  'admin.outbox.logged': 'registrado',
  'admin.tpl.approved': 'aprobada',
  'admin.tpl.rejected': 'rechazada',
  'admin.tpl.paused': 'pausada',
  'admin.tpl.disabled': 'desactivada',
  'admin.outbox.failed': 'falló',
  'admin.noClub': 'Todavía no está en ningún club.',
  'admin.inClub': 'Ya está en un club.',
  'admin.moreWait': '{n} más esperan',
  'admin.moreWaitOne': '1 más espera',
  'admin.tpl.review': 'en revisión',
  'admin.tpl.send': 'Enviar a revisión',
  'admin.tpl.resend': 'Volver a enviar a revisión',
  'inv.notFound': 'Invitación no encontrada',
  'club.about.sent': 'Enviado a los admins para aprobar.',
  'club.about.willApprove': 'Un admin va a aprobar tus cambios',
  'club.about.submit': 'Enviar para aprobación',
  'club.cat.new': 'Nueva categoría',
  'club.cat.delete': 'Eliminar categoría',
  'club.cat.add': 'Añadir categoría',
  'club.about.editLink': 'editar descripción y enlaces',
  'club.underReview': 'en revisión',
  'club.cal.every': 'cada evento, en tu calendario',
  'club.roster.recorded': 'Cada una la registró quien organizó, después del evento.',
  'club.roster.fromRsvp': 'Una parte se cuenta desde los RSVP: eventos que terminaron antes de que existiera la lista.',
  'club.roster.allRsvp': 'Se cuenta desde los RSVP. En esos eventos nadie pasó lista, así que es una estimación.',
  'club.roster.none': 'sin asistencias todavía',
  'club.roster.remove': 'Solicitar remoción',
  'club.cal.copyFailed': 'No se pudo copiar. Mantén presionado el enlace.',
  'club.cal.newLink': 'Enlace nuevo. El anterior dejó de funcionar.',
  'club.cal.changeFailed': 'No se pudo cambiar el enlace.',
  'club.invite.emailPh': 'nombre@correo.com',
  'club.invite.note': 'Los organizadores invitan miembros. Solo un admin asigna organizadores o admins.',
  'club.lastAdmin': 'Eres el último admin',
  'club.reinvited': 'Te pueden volver a invitar después',
  'club.onlyMember': 'para su único miembro',
  'form.catNew': 'Nueva categoría…',
  'form.askedAdmin': 'Se lo pedimos a la administración del club. Mientras, el evento se crea igual.',
  'form.grain.fine': 'Más preciso. La cuadrícula sale al doble de larga.',
  'photos.uploadFailed': 'No se pudo subir la foto.',
  'photos.removeFailed': 'No se pudo quitar la foto.',
  'event.binNoPhotos2': 'Este evento está en la papelera, no se pueden agregar fotos.',
  'event.onlyWent2': 'Solo quien fue al evento puede agregar fotos.',
  'event.saidYesOne': '1 persona ya dijo que va',
  'event.saidYesMany': '{n} personas ya dijeron que van',
  'event.maybe': 'quizás',
  'event.askedJoin': 'Ya pediste unirte. Un organizador o admin te va a dejar entrar pronto.',
  'event.guestJoinAsk': 'Puedes confirmar y aportar aquí. ¿Quieres también el resto de eventos del club?',
  'event.guestOk': 'Puedes confirmar y aportar en este evento aunque no seas del club.',
  'event.saidYouGo': 'Vas a ir',
  'event.saidMaybe': 'Dijiste que quizás',
  'event.saidNo': 'Dijiste que no puedes',
  'event.pending.none': 'Ni sí, ni no, ni disponibilidad.',
  'event.pending.reminded': 'Ya les llegó el recordatorio. Solo se manda una vez.',
  'event.rsvp.saidComing': '{n} dijo que venía',
  'pay.bank_account': 'Cuenta bancaria',
  'pay.bank_code': 'CLABE',
  'pay.card': 'Tarjeta',
  'pay.cash': 'Efectivo',
  'pay.other': 'Otro',
  'pay.add': 'Agregar forma de pago',
  'pay.note': 'Esto es lo que ve quien te queda a deber, para saber cómo pagarte. Solo lo ven las personas que comparten un club contigo.',
  'account.wa.notAdded': 'no agregado',
  'account.wa.add': 'agregar',
  'common.change': 'cambiar',
  'account.places.note': 'Aparecen como {yours} cuando pones el lugar de un evento que organizas, con su pin.',
  'push.meanwhile': 'Mientras tanto no se pierde nada: los avisos te siguen llegando por correo y WhatsApp.',
  'push.incompatible': 'no compatible',
  'club.change.about': 'Acerca de',
  'club.change.category_add': 'Nueva categoría',
  'club.change.category_edit': 'Editar categoría',
  'club.change.category_delete': 'Eliminar categoría',
  'club.change.banner': 'Portada',
  'club.change.avatar': 'Foto del club',
  'club.change.member_removal': 'Quitar miembro',
  'event.capacityFor': 'cupo para {n}',
  'event.saidYes': '{n} personas ya dijeron que van.',
  'event.saidYesJustOne': '1 persona ya dijo que va.',
  'search.upcomingOne': '{n} próximo',
  'search.upcomingMany': '{n} próximos',
  'admin.moreWaitLabel': '{n} más esperan',
  'club.forOneMember': ' para su único miembro',
  'club.forNMembers': ' para sus {n} miembros',
  'form.askedAdminNoCat': 'Se lo pedimos a la administración del club. Mientras, el evento se crea sin categoría.',
  'inv.acceptJoins': 'Al aceptar te unes a «{club}».',
  'signin.noAccountEmailLong': 'Si ese correo no tiene cuenta en Hive, no llegará nada. Prueba con tu WhatsApp, o pide a quien organiza que te invite.',
  'club.roster.fromRsvp2': 'Una parte se cuenta desde los RSVP: eventos que terminaron antes de que se pasara lista.',
  'club.roster.allRsvp2': 'Se cuenta desde los RSVP. En esos eventos nadie pasó lista, así que es quien dijo que iba.',
  'rsvp.maybe': 'Quizás',
  'admin.noClubYet': 'Todavía no está en ningún club.',
  'admin.alreadyClub': 'Ya está en un club.',
  'admin.morePending': '· {n} más esperan, más viejo primero',
  'admin.morePendingOne': '· 1 más espera, más viejo primero',
  'search.upcomingCount': '{n} próximos',
  'search.upcomingCountOne': '1 próximo',
  'money.saysPaid': '{from} dice que pagó {amount} a {to}',
  'event.andMore': ' y {n} más',
  'event.rollcall.cameOne': '1 dijo que venía',
  'event.rollcall.cameMany': '{n} dijeron que venían',
  'event.rollcall.tapAbsent': 'Toca a quien no llegó, casi siempre no es nadie.',
  'event.inviteOnlyNote': 'Este evento es solo con invitación (o el enlace no es correcto). Pide a quien organiza que te invite.',
  'cal.add': 'Agregar a tu calendario',
  'cal.google': 'Google Calendar',
  'cal.other': 'Apple, Outlook y otros',
  'roll.take': 'Pasar lista',
  'roll.quick': 'Como quince segundos. Solo la ve quien organiza, y se puede corregir después.',
  'roll.fix': 'Corregir',
  'roll.allCame': 'Vinieron todos',
  'roll.nobody': 'Nadie',
  'roll.saved': 'Lista guardada.',
  'claim.mine': 'Me lo pido',
  'claim.yes': 'Sí, yo lo traigo',
  'claim.openSpot': 'Abrir un lugar (sube al siguiente)',
  'claim.note': 'En cuanto te lo apuntes, el club cuenta contigo. Solo quien organiza puede reasignarlo después.',
  'dup.title': 'Duplicar este evento',
  'dup.notice': 'Al crearlo se le avisa a todo el club de inmediato, por correo y WhatsApp. No hay paso de borrador y el aviso no se puede retirar.',
  'dup.weekNote': 'El día lo siguen eligiendo los miembros dentro de esa semana. Esto solo dice dónde buscar.',
  'event.cancelEvent': 'Cancelar evento',
  'event.deleteEvent': 'Eliminar evento',
  'event.prev': 'Anterior',
  'event.next': 'Siguiente',
  'poll.new': 'Nueva encuesta',
  'poll.create': 'Crear encuesta',
  'poll.multi': 'varias opciones',
  'poll.resultsAtClose': 'resultados al cerrar',
  'money.expenses': 'Gastos',
  'money.balances': 'Balances',
  'money.saveExpense': 'Guardar gasto',
  'money.youPaidNote': 'Lo pagaste tú, así que te deben el total; se reparte en partes iguales entre quienes marques.',
  'club.theClub': 'el club',
  'common.seeAllF': 'Ver todas',
  'event.fixRange': 'Fijar este rango',
  'event.reused': 'Esta lista viene de la vez pasada. Nadie ha apartado nada todavía, y así debe ser: apártalo otra vez si lo llevas.',
  'event.cancelledLong': 'Este evento se canceló. RSVPs y aportaciones están cerrados, todo lo demás se queda como historial. Se avisó a todos por correo y WhatsApp.',
  'event.invite': 'Invitar',
  'event.held': 'Evento celebrado',
  'event.closedBy': 'Cerrado por {name}',
  'money.paidBy': '· pagó {name}',
  'money.betweenOne': '{amount} entre 1 persona',
  'money.betweenMany': '{amount} entre {n} personas',
  'money.upDownNote': 'Si la cantidad sube, se abre una deuda nueva por la diferencia. Si baja, se debe la diferencia de vuelta a quien ya pagó.',
  'photos.empty': 'Todavía no hay fotos. Las que subas las ve quien estuvo en el evento.',
  'photos.add': 'Agregar',
  'event.pay': 'Pagar',
  'event.goingLine': 'van {going} · no van {out}',
  'event.you': 'Tú',
  'line.nobodyAnswered': 'Nadie ha contestado',
  'line.youGo': 'Vas',
  'line.youAndMore': 'Vas, y {n} más',
  'line.nobodyYet': 'Nadie va todavía',
  'line.nobodyYetMaybe': 'Nadie va todavía, dijiste quizás',
  'line.nobodyYetYouOut': 'Nadie va todavía, tú tampoco',
  'line.going': 'van {n}',
  'line.goingMaybe': 'van {n}, dijiste quizás',
  'line.goingYouOut': 'van {n}, tú no',
  'line.goingUnanswered': 'van {n}, no has dicho',
  'club.noEventsYet': 'Todavía sin eventos.',
  'time.never': 'nunca',
  'time.soon': 'próximamente',
  'time.today': 'hoy',
  'time.yesterday': 'ayer',
  'time.daysAgo': 'hace {n} días',
  'time.weekAgo': 'hace 1 semana',
  'time.weeksAgo': 'hace {n} semanas',
  'time.monthAgo': 'hace 1 mes',
  'time.monthsAgo': 'hace {n} meses',
  'event.goingN': 'van {n}',
  'event.ofCapacity': ' de {n}',
  'event.waitingN': ' · {n} en espera',
  'event.notGoingN': ' · no van {n}',
  'event.maybeN': ' · quizás {n}',
  'event.goingCount': '{n} van',
  'details.label': 'Detalles, organizadores, calendario',
  'signin.tagline': 'Tu club, organizado.',
  'signin.welcome': 'Bienvenido al enjambre. Busquemos fecha.',
  'signin.field': 'Tu correo o WhatsApp',
  'signin.hint': 'Con tu correo o tu WhatsApp. En los dos casos te llega un código de 6 dígitos.',
  'signin.noPasswords': 'Sin contraseñas.',
  'signin.invited': '¿Te invitaron por WhatsApp? Usa el enlace que te llegó.',
  'signin.code': 'Tu código',
  'signin.codeSent': 'Te mandamos un código de 6 dígitos.',
  'signin.resend': 'Reenviar',
  'signin.resendLong': '¿No te llegó? Pídelo de nuevo',
  'signin.sending': 'Enviando…',
  // The line under the field, which changes as they type. For a number it
  // carries the normalized form, so the +52 nobody typed is visible before the
  // message goes somewhere else.
  'signin.helper.email': 'Te mandamos un código de 6 dígitos a ese correo.',
  'signin.helper.phone': 'Te mandamos un código de 6 dígitos a {display} por WhatsApp.',
  'signin.helper.short': 'Un número recibe el código por WhatsApp. Los mexicanos no necesitan el +52.',
  // The button says where the code is going: on a field that takes two kinds
  // of thing, the label is the clearest confirmation of which one it read.
  'signin.action.email': 'Mándame el código por correo',
  'signin.action.whatsapp': 'Mándame el código por WhatsApp',

  // -- pending --------------------------------------------------------------
  'pending.title': 'Estás en la fila',
  'pending.body': 'Quien administra Hive tiene que aprobar tu cuenta. Te avisamos en cuanto esté lista; ya sabemos que llegaste.',
  'pending.next': 'Quien administra revisa las cuentas nuevas. Eres quien sigue.',
  'pending.buzz': 'Zumbando en la fila…',
  'pending.remind': 'Recuérdales',
} as const

export const EN: Partial<Record<keyof typeof ES, string>> = {
  // -- chrome ---------------------------------------------------------------
  'tab.clubs': 'Clubs',
  'tab.events': 'Events',
  'tab.home': 'Home',
  'tab.plate': 'Plate',
  'tab.you': 'You',

  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.saving': 'Saving…',
  'common.saved': 'Done',
  'common.remove': 'Remove',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.add': 'Add',
  'common.close': 'Close',
  'common.back': 'Back',
  'common.confirm': 'Confirm',
  'common.continue': 'Continue',
  'common.copy': 'Copy',
  'common.copied': 'Copied',
  'common.seeAll': 'See all',
  'common.optional': 'Optional',
  'common.none': 'None',
  'common.search': 'Search events, clubs, people',
  'common.retry': 'Try again.',

  // -- home -----------------------------------------------------------------
  'home.greeting': 'hi, {name}',
  'home.plate': 'On your plate',
  'home.plate.more': '+{n} more',
  'home.upcoming': 'Coming up',
  'home.upcoming.empty': 'Nothing on yet.',
  'home.history': 'Your history',
  'home.clubs': 'Your clubs',
  'home.clubs.empty.title': "You're not in a club yet",
  'home.clubs.empty.hint': 'Ask an organizer to invite you, or start your own.',
  'home.away': 'While you were away',
  'home.plate.clear': "All clear. Nothing needs you right now.",
  'home.clubs.empty.short': 'Ask an organizer to invite you.',
  'home.createClub': 'Create a club',

  // -- clubs ----------------------------------------------------------------
  'clubs.title': 'Clubs',
  'clubs.quiet': 'Nothing planned',
  'clubs.quietSince': 'Quiet since {month}.',
  'clubs.newEvent': 'New event',
  'clubs.empty.title': "You're not in a club yet",
  'clubs.empty.hint': 'Ask an organizer to invite you, or start your own.',

  // -- events ---------------------------------------------------------------
  'events.title': 'Events',
  'events.lede': 'Everything your clubs have done.',
  'events.filters': 'Filters',
  'events.filter.club': 'Club',
  'events.filter.cat': 'Category',
  'events.filter.person': 'Who went',
  'events.filter.when': 'When',
  'events.filter.place': 'Place',
  'events.filter.sort': 'Sort',
  'events.filter.money': 'Money',
  'events.filter.all': 'All',
  'events.filter.allF': 'All',
  'events.filter.anyone': 'Anyone',
  'events.filter.anyDate': 'Any date',
  'events.filter.upcoming': 'Upcoming',
  'events.filter.past': 'Past',
  'events.filter.newest': 'Newest',
  'events.filter.oldest': 'Oldest',
  'events.filter.mostOwed': 'Most owed',
  'events.filter.owedOnly': 'Only with money outstanding',
  'events.filter.you': 'You',
  'events.filter.clear': 'Remove filter {label}',
  'events.count': '{n} events',
  'events.count.one': '1 event',
  'events.owed.total': 'outstanding in total',
  'events.owed.you': 'you still owe',
  'events.owed.person': '{name} still owes',
  'events.empty.title': 'No events match.',
  'events.empty.hint': 'Loosen a filter.',
  'events.noPlace': 'no place',
  'events.went': '{n} went',
  'events.noCategory': 'no category',

  // -- when -----------------------------------------------------------------
  'when.finding': 'Finding a date',
  'when.today': 'Today',
  'when.tomorrow': 'Tomorrow',

  // -- account --------------------------------------------------------------
  'account.title': 'My account',
  'account.lede': 'Your bug, how you get in, how we reach you and how you get paid.',
  'account.group.you': 'You',
  'account.group.signin': 'How you get in',
  'account.group.notify': 'How Hive reaches you',
  'account.group.money': 'How you get paid',
  'account.group.places': 'Places you can host',
  'account.group.platform': 'Platform',
  'account.signin.note': 'You get in with a link to your email or a code on WhatsApp. No passwords.',
  'account.email': 'Email',
  'account.email.none': 'no email',
  'account.verified': 'verified',
  'account.name': 'Display name',
  'account.photo': 'Or use your own photo',
  'account.photo.change': 'Change photo',
  'account.photo.back': 'Back to my bug',
  'account.photo.failed': "Couldn't upload the photo. Try again.",
  'account.bug.hint': 'Pick a bug and a colour so the club can tell everyone apart at a glance.',
  'account.photo.hint': 'Your photo shows instead of your bug, with the same hexagon crop.',
  'account.crop.title': 'Frame your photo',

  'lang.label': 'Language',
  'lang.auto': 'Follow your phone',
  'lang.es': 'Español',
  'lang.en': 'English',

  'platform.door': 'Admin panel',
  'platform.meta': 'accounts and delivery',

  'danger.zone': 'Danger zone',
  'danger.signout': 'Sign out',
  'danger.delete': 'Delete account',
  'danger.note': "Your past attendance and expenses stay in your clubs' history; your profile and the way you sign in are deleted.",

  // -- notifications --------------------------------------------------------
  'notif.email': 'Email',
  'notif.whatsapp': 'WhatsApp',
  'notif.push': 'Alerts',
  'notif.scope.you': 'you',
  'notif.scope.device': 'this device',
  'notif.needWhatsapp': 'Add your WhatsApp number above to switch that column on.',
  'notif.kept': "What you choose here is saved and starts applying the moment it's on.",
  'notif.topic.new_event': 'New events in my clubs',
  'notif.topic.reminders': 'Reminder the day of the event',
  'notif.topic.rsvp_waitlist': 'RSVP and waitlist',
  'notif.topic.payments': 'Payments (paid or confirmed)',
  'notif.topic.approvals': 'Admin decisions (changes and requests)',

  'push.off': 'Alerts are off on this device.',
  'push.denied': 'This browser is blocking alerts on this device.',
  'push.install': 'On iPhone, Hive has to be on your Home Screen before alerts can be turned on.',
  'push.unsupported': "This browser can't show alerts.",

  // -- plate ----------------------------------------------------------------
  'plate.title': 'Plate',
  'plate.pay': 'Payments · to do',
  'plate.pay.oldest': 'oldest first',
  'plate.owedToYou': 'Owed to you',
  'plate.awaiting': 'Waiting on your confirmation',
  'plate.empty.title': 'Nothing pending',
  'plate.empty.hint': 'When somebody owes you or an answer is missing, it shows up here.',
  'plate.owe': 'You owe {name} {amount}',
  'plate.paidYou': '{name} says they paid you {amount}',
  'plate.rsvp': 'Are you going?',
  'plate.availability': 'Mark when you can',
  'plate.vote': 'Your vote is missing',
  'plate.later': 'Not yet',
  'plate.payTo': 'Pay {name}',
  'plate.lede': 'Everything open before each event closes. Act here, or tap the event name to open it.',
  'plate.clear.title': 'All clear.',
  'plate.clear.hint': 'Nothing needs you right now. Enjoy the buzz.',
  'plate.waiting': "They're waiting on you",
  'plate.tasks': 'Tasks',
  'plate.bringing': "You're bringing",
  'plate.put': '{name} put in {amount}',

  // -- event ----------------------------------------------------------------
  'event.going': "Who's going",
  'event.contributions': 'What people bring',
  'event.polls': 'Polls',
  'event.money': 'Money',
  'event.photos': 'Photos',
  'event.thread': 'Thread',
  'event.elsewhere': 'Elsewhere',
  'event.details': 'Details, organizers, calendar',
  'event.noPlaceYet': 'No place yet',
  'event.setPlace': 'Set a place',
  'event.changePlace': 'Change place',
  'event.directions': 'Directions',
  'event.rsvp.ask': 'Are you going?',
  'event.rsvp.going': "I'm in",
  'event.rsvp.maybe': 'Maybe',
  'event.rsvp.no': "Can't",
  'event.rsvp.change': 'change',
  'event.cancelled': 'cancelled',
  'event.waitlisted': 'waitlisted',
  'event.youGo': 'going',
  'event.youWent': 'went',
  'event.guestName': "Your guest's name",
  'event.bringSomeone': 'Bring someone',
  'event.noRoomGuests': 'There is no room to bring anybody else.',
  'event.waitlist.note': 'When a seat frees up, whoever is first in line gets it and we tell them by email and WhatsApp.',
  'event.sheet': 'Details',
  'event.closed': 'RSVPs and the bring list are closed. Everything else stays as history.',
  'event.contrib.empty': 'Nobody is bringing anything yet. Start the list.',
  'event.organizers': 'Organizers',
  'event.stillFinding': "Still finding a date. Mark when you can below.",
  'event.markAvailability': 'You still need to mark when you can',
  'event.otherEvents': 'Other events from this club',
  'event.undo': 'undo',
  'event.done': 'done',
  'event.host': 'host',
  'event.pending': 'pending',
  'event.task': 'task',
  'event.dontForget': "don't forget",

  // -- create / edit event --------------------------------------------------
  'form.title': 'Title',
  'form.title.ph': 'Game night',
  'form.title.missing': 'Give it a title first.',
  'form.category': 'Category',
  'form.category.none': 'No category',
  'form.category.name': 'Category name',
  'form.category.ph': 'Wine tasting',
  'form.place': 'Place (optional)',
  'form.findDate': 'Find a date',
  'form.window': 'The window of days and times members mark themselves free in.',
  'form.from': 'From',
  'form.to': 'To',
  'form.timeFrom': 'From',
  'form.timeTo': 'To',
  'form.cells': 'Cells',
  'form.grain': 'How finely people mark',
  'form.extras': 'Add if you need it',
  'form.cap.offer': 'A limit on how many fit',
  'form.cap.consequence': 'With a waitlist once it fills',
  'form.cap.label': 'Capacity',
  'form.cap.max': 'Max',
  'form.waitlist': 'waitlist',
  'form.cap.hint': 'With no capacity the event never fills, and nobody waits.',
  'form.guests.offer': 'Let people bring someone',
  'form.guests.consequence': 'A partner, a couple of friends',
  'form.guests.each': 'each member can bring',
  'form.guests.less': 'one fewer',
  'form.guests.more': 'one more',
  'form.guests.hint': 'Every guest takes a seat, the same as a member.',
  'form.deadline.offer': 'A date to confirm by',
  'form.deadline.consequence': "Anyone who hasn't answered gets a reminder",
  'form.deadline.label': 'Confirm before',
  'form.join': 'Who can get in with the link',
  'form.join.members': 'club members only',
  'form.join.link': 'anyone with the link',
  'form.join.invite': 'invite only',
  'form.create': 'Create event',
  'form.createAndAsk': 'Create and ask for times',
  'form.extras.hint': 'Most events need none of these. The bring list and the polls are added on the event itself, once it exists and people can actually claim things.',
  'form.saveChanges': 'Save changes',

  // -- club page ------------------------------------------------------------
  'club.notMember': "This club doesn't exist, or you're not a member yet. Ask for the invite link.",
  'club.the': 'The club',
  'club.members': 'Members',
  'club.subscribe': 'Subscribe',
  'club.pastEvents': 'Past events',
  'club.removeMember': 'Remove member',
  'club.approve': 'Approve',
  'club.decline': 'Decline',
  'club.emptyCategory': 'Nothing in this category yet.',
  'club.allCategories': 'All',

  // -- push row -------------------------------------------------------------
  'push.title': 'Alerts',
  'push.enable': 'Turn on',
  'push.on': 'on',
  'push.blocked': 'blocked',
  'push.unsupported.title': "This browser doesn't do alerts",
  'push.alsoOn': 'Also on',
  'push.what': 'A note on your screen when something happens, without opening the app. This browser only.',
  'push.working': 'Alerts reach this browser. They are per device: on your other phone you turn them on separately.',
  'push.blocked.help': 'This browser is blocking them. Follow the steps below to unblock.',
  'push.step1': '1. Tap the padlock or the three dots next to the address.',
  'push.step2': '2. Find Notifications and switch it to Allow.',
  'push.step3': '3. Come back here and reload the page.',
  'push.unsupported.note': "This browser doesn't do alerts. We'll keep reaching you by email and WhatsApp.",

  // -- money ----------------------------------------------------------------
  'money.amount': 'Amount',
  'money.method': 'Method',
  'money.to': 'To',
  'money.receipt': 'Payment receipt',
  'money.receipt.upload': 'Tap to upload a screenshot of the transfer',
  'money.receipt.private': 'Only you can see this, because you are the one who received it.',
  'money.how': 'How did you pay?',
  'money.pay': 'Pay',
  'money.confirm': 'Confirm',
  'money.confirmPayment': 'Confirm payment',
  'money.confirmReceived': 'Confirm received',
  'club.creating': 'Creating…',
  'money.expense.add': 'Add an expense',
  'money.expense.edit': 'Edit expense',
  'money.expense.what': 'What it was',
  'money.expense.split': 'Split between',
  'money.expense.youPaid': 'You paid it',
  'money.expense.settled': 'Payments already confirmed stay as they are',

  // -- contributions --------------------------------------------------------
  'contrib.add': 'Add a contribution',
  'contrib.edit': 'Edit contribution',
  'contrib.what': 'What',
  'contrib.type': 'Type',
  'contrib.forWhom': 'For whom',
  'contrib.qty': 'Quantity (optional)',
  'contrib.qty.ph': 'quantity',
  'contrib.bring': 'bring something',
  'contrib.task': 'task',
  'contrib.forMe': 'for me',
  'contrib.open': 'open (for somebody to claim)',
  'contrib.onlyYou': 'You claim it yourself. Assigning something to somebody else is an organizer\'s job.',


  // -- roles ----------------------------------------------------------------
  'role.admin': 'admin',
  'role.organizer': 'organizer',
  'role.member': 'member',
  'role.guest': 'guest',

  // -- club admin -----------------------------------------------------------
  'club.about.edit': 'Edit about',
  'club.about.desc': 'Description',
  'club.about.links': 'Links',
  'club.about.removeLink': 'Remove link',
  'club.about.linkLabel': 'Label',
  'club.about.linkUrl': 'link.com/…',
  'club.avatar.change': "Change the club's photo",
  'club.avatar.crop': "Frame the club's photo",
  'club.banner.change': 'Change cover',
  'club.banner.crop': 'Frame the cover',
  'club.cal.regen': 'Change the calendar link?',
  'club.cal.regen.warn': 'Anyone already subscribed will have to add it again',
  'club.cat': 'Category',
  'club.cat.edit': 'Edit category',
  'club.cat.name': 'Category name',
  'club.cat.ph': 'Board games',
  'club.cat.emoji': 'Emoji',
  'club.leave.warn': "You leave the roster and stop seeing this club's events. Your history stays intact.",
  'club.irreversible': "This can't be undone",
  'club.gotIt': 'Got it',
  'club.invite.email': 'Email',
  'club.invite.whatsapp': 'Or WhatsApp',
  'club.invite.role': 'Role',
  'club.invite.auto': 'Leave an email and the invitation sends itself',
  'club.joinLink': 'Link to join',
  'club.revoke': 'Revoke',
  'club.join.anyone': 'anyone with the link (needs approval)',
  'club.join.invite': 'invite only',
  'club.join.no': 'nobody',
  'club.new': 'New club',
  'club.create': 'Create club',
  'club.name': 'Club name',
  'club.name.ph': 'Thursdays',
  'club.create.modal': 'Create a club',
  'club.create.firstAdmin': "You'll be its first admin",
  'club.create.next': 'Next: invite people and create your first event.',
  'club.notFound': 'Club not found',
  'club.private': 'Private club',
  'club.joinTo': 'Join',
  'club.notMemberShort': "This club doesn't exist, or you're not a member.",
  'club.newEvent.title': 'New event',

  // -- account extras -------------------------------------------------------
  'account.profile': 'Profile',
  'account.yourBug': 'Your bug',
  'account.delete.confirm': 'Delete your account?',
  'account.delete.type': 'Type DELETE to confirm',
  'account.irreversible': "This can't be undone",
  'account.pay.remove': 'Remove payment method',
  'account.pay.ph': 'Number, handle, note…',
  'account.place.name': 'Name',
  'account.place.addr': 'Address',
  'account.place.ph': "Marta's place",
  'account.place.missing': 'The name and the address are missing.',
  'account.place.noPin': 'No pin. The map looks it up from the address.',
  'account.place.yours': 'your places',
  'account.wa.number': 'WhatsApp number',
  'account.wa.ph': '+52 55 1234 5678',
  'account.wa.change': 'Change number',
  'account.wa.remove': 'Remove your WhatsApp?',

  // -- event extras ---------------------------------------------------------
  'event.rollcall.who': 'Who came?',
  'event.rollcall.tap': "Tap whoever didn't make it.",
  'event.rollcall.private': 'Nobody is told. You can correct it later.',
  'event.rollcall.absent': "didn't come",
  'event.claim.ask': 'Are you bringing it?',
  'event.coorg.add': 'Add a co-organizer',
  'event.coorg.can': 'Can edit the event and manage who is going',
  'event.coorg.none': 'There are no other club members to invite.',
  'event.coorg.note': 'Only club organizers and admins can co-organize. The invitation goes out by email and WhatsApp.',
  'event.coorg.invite': 'Invite',
  'event.again': 'Again?',
  'event.notNow': 'Not now',
  'event.dup': 'Duplicate',
  'event.dup.title': 'Duplicate this event',
  'event.dup.newDate': 'New date',
  'event.dup.week': 'Which week is it looking in?',
  'event.dup.fresh': 'Starts fresh',
  'event.dup.kept': 'Carried over',
  'event.dup.hint': "Nobody is signed up and nothing is claimed yet. That's normal for a new night, not everyone dropping out.",
  'event.edit': 'Edit event',
  'event.settle': 'Settle up',
  'event.toConfirm': 'Payments to confirm',
  'event.noExpenses': 'No expenses yet.',
  'event.byHand': 'by hand',
  'event.withdraw': 'withdraw',
  'event.bestSlots': 'Best slots',
  'event.remembered': 'remembered',

  // -- admin ----------------------------------------------------------------
  'admin.title': 'Admin',
  'admin.none': 'Nobody is waiting to be verified.',
  'admin.verify': 'Verify',
  'admin.disable': 'disable',
  'admin.reactivate': 'reactivate',
  'admin.users': 'Users',
  'admin.delivery': 'Delivery',
  'admin.templates': 'Templates',
  'admin.outbox.empty': 'No messages have gone out yet.',
  'admin.tpl.subject': 'Subject',
  'admin.tpl.noWa': 'not sent to WhatsApp',


  // -- invitations ----------------------------------------------------------
  'inv.link': 'Event link',
  'inv.who': 'Who can get in with it',
  'inv.personal': 'Personal invitation',
  'inv.none': "You haven't invited anybody yet",
  'inv.none.hint': 'Share the event link or send a personal invitation.',
  'inv.email.ph': 'email',
  'inv.wa.ph': 'or WhatsApp (+52 …)',
  'inv.accepted': 'accepted',
  'inv.pending': 'pending',
  'inv.expired': 'expired',
  'inv.anyone': 'Anyone with the link',
  'inv.inviteOnly': 'Invite only',
  'inv.membersOnly': 'Club members only',
  'inv.no': 'nobody',
  'inv.youWere': "You're invited",
  'inv.used': 'This invitation has already been used',
  'inv.tooLate': 'This invitation has expired',
  'inv.noted': 'Noted',
  'inv.alreadyIn': "You're already in",
  'inv.yourEmail': 'Your email',
  'inv.email.example': 'you@email.com',

  // -- place picker ---------------------------------------------------------
  'place.ph': "Somebody's place, or an address",
  'place.yours': 'Your places',
  'place.recent': 'Recent',
  'place.drag': 'Drag the pin or tap the map to move it. This is where people will arrive.',
  'place.tapMap': 'Tap the map to drop the exact pin.',
  'place.searching': 'Looking up the address…',

  // -- polls ----------------------------------------------------------------
  'poll.empty': 'Nobody has asked anything yet.',
  'poll.hidden': 'Results show once the poll closes.',
  'poll.visible': 'The vote stays visible even after an option is picked.',
  'poll.closed': 'closed',
  'poll.pick': 'pick',

  // -- misc -----------------------------------------------------------------
  'pwa.title': 'Keep Hive to hand',
  'pwa.hide': 'Hide',
  'thread.ph': 'Say something to the group…',
  'thread.send': 'Send',
  'thread.delete': 'Delete',
  'signin.ph': 'you@email.com  ·  55 1234 5678',


  // -- sign in flow ---------------------------------------------------------
  'signin.linkUsed': 'That link has been used or has expired. Each link works once (sometimes your email opens it before you do). Ask for a new one.',
  'signin.tooMany': 'Too many tries in a row. Wait a minute and ask for the link again.',
  'signin.sendFailed': "We couldn't finish sending. Check your connection and try again.",
  'signin.checkEmail': 'Check your email',
  'signin.changeNumber': 'Change number',
  'signin.noAccountPhone': "If that number has no Hive account, nothing will arrive. Try your email.",
  'signin.noAccountEmail': "If that email has no Hive account, nothing will arrive. Try your WhatsApp.",

  // -- invite ---------------------------------------------------------------
  'invite.findingDate': "They're still finding a date between them.",
  'invite.noPlace': 'The place is still to be decided.',
  'invite.nobodyYet': 'Nobody has confirmed yet',
  'invite.accept?': 'Accept the invitation?',
  'invite.accept': 'Accept invitation',
  'invite.saidNo': "You said you can't. Undo",
  'invite.changedMind': "Changed my mind, I'm in",
  'invite.noForms': 'No passwords, no forms.',

  // -- plate loud -----------------------------------------------------------
  'plate.markWhen': 'Mark when you can',
  'plate.needsAll': 'Nobody can fix the date until everyone answers.',
  'plate.rsvpWhy': 'Knowing who is going decides the place and what to bring.',
  'plate.alsoToPay': 'Also to pay',
  'plate.done!': 'Done!',
  'plate.taskDone': 'Task done. One less thing on your plate.',
  'plate.bringNoted': "Noted as brought. Don't forget it at the door.",
  'plate.markTaskDone': 'Mark the task as done?',
  'plate.markBrought': 'Mark as brought?',
  'plate.yesDone': "Yes, it's done",
  'plate.yesBring': "Yes, I'll bring it",
  'plate.taskWarn': "Marking it done removes it from everyone's list. If you get it wrong, it can be undone.",
  'plate.bringWarn': 'Confirming it means the club counts it as covered. If you get it wrong, it can be undone.',

  // -- grid -----------------------------------------------------------------
  'grid.markMine': 'Mark mine',
  'grid.dragDay': 'Drag across the day to pick the exact range.',
  'grid.holdDrag': 'Hold and drag across a day. The more honey, the more people can.',
  'grid.nothingPicked': 'Nothing picked yet.',
  'grid.alreadyReminded': 'We had already reminded them',
  'grid.autoReminder': 'It sends itself when the confirm deadline passes. It only arrives once.',

  // -- sign in --------------------------------------------------------------
  'signin.checkWa': 'Check your WhatsApp',
  'signin.changeEmail': 'Change email',
  'signin.checkEmailLink': 'Check your email. We sent you a link, open it in this same browser to come back here.',
  'invite.goingOne': '{n} person is going',
  'invite.goingMany': '{n} people are going',
  'invite.oneMoment': 'One moment…',
  'invite.telling': 'Letting them know…',
  'invite.cant': "I can't make it",

  'inv.notFound.hint': 'That link is not valid. Ask whoever organizes it to send you another.',
  'inv.sub.eventClub.by': '{name} invited you along with «{club}».',
  'inv.sub.eventClub': 'You were invited along with «{club}».',
  'inv.sub.by': '{name} invited you to join.',
  'inv.sub': 'You were invited to join.',
  'invite.spotsOne': '1 spot left of {capacity}',
  'invite.spotsMany': '{n} spots left of {capacity}',
  'invite.full': 'all {capacity} spots are taken, you would go on the waitlist',
  'invite.expired.by': 'Links last 30 days. Ask {name} for another and you are in.',
  'invite.expired': 'Links last 30 days. Ask whoever invited you for another and you are in.',
  'inv.alreadyIn.club': 'You used this invitation and you are already part of «{club}».',
  'inv.alreadyIn.hint': 'You used this invitation.',
  'inv.goEvent': 'Go to the event',
  'inv.goClub': 'Go to the club',
  'inv.used.by': 'Somebody else opened it first. Ask {name} for another if it was for you.',
  'inv.used.hint': 'Somebody else opened it first. Ask whoever invited you for another if it was for you.',
  'inv.joinClub?': 'Join «{club}»?',
  'inv.signedIn.club':
    'You are already signed in. Accepting joins you to «{club}», and whoever organizes it will see your name.',
  'inv.signedIn.event':
    'You are already signed in. Accepting puts you in, and whoever organizes it will see your name.',
  'invite.declined.by': "{name} will see that you can't. If you change your mind, this link still works.",
  'invite.declined': "Whoever invited you will see that you can't. If you change your mind, this link still works.",
  'inv.sentTo': 'We sent a link to {email}. Open it in this same browser.',
  'inv.emailIntro': 'Put in your email and we will send you a link to get in. No passwords.',
  'inv.phoneOnly':
    'You were invited over WhatsApp. For now you get in with email: put yours in and your invitation stays linked.',

  'club.notFound.hint': 'That link is not valid. Ask whoever runs the club to send you another.',
  'club.private.hint': 'This club is join-by-invitation only. Ask a member to invite you.',
  'club.join.sent':
    'Check your email. We sent you a link: open it in this same browser to come back here and ask to join.',
  'club.request.intro':
    'Send your request to join. Whoever runs the club reviews it before you are in.',
  'club.request.action': 'Ask to join',
  'club.request.sent': 'Your request is in. Whoever runs «{club}» will review it.',
  'common.sending': 'Sending…',
  'plate.toPay': 'Payments · to do',
  'money.markPaid': 'Mark as paid',
  'grid.fixTime': 'Fix the time',
  'grid.slotsMarked': '{n} slots marked',
  'grid.slotMarked': '{n} slot marked',
  'grid.savingDots': ' · saving…',
  'grid.savedDots': ' · saved',
  'common.notSaved': "Couldn't save.",
  'common.needName': 'You need a display name.',
  'account.place.save': 'Save place',
  'account.thisDevice': 'this device',
  'push.thisBrowser': 'this browser',
  'push.onDevice': '{browser} on {os}',
  'push.alertsIn': 'Alerts in {device}',
  'push.turningOn': 'Turning on…',
  'push.turnedOn': 'Alerts on for this device.',
  'push.turnedOff': 'Alerts off for this device.',
  'push.failOn': "Couldn't turn alerts on.",
  'push.failOff': "Couldn't turn alerts off.",
  'account.wa.done': "Done, we've told you on WhatsApp",
  'account.wa.send': 'Send code',
  'pending.disabled': 'Your account is disabled',
  'pending.disabled.body': "For now you can't get into your clubs or their events. If you think that's a mistake, write to whoever administers it.",
  'pending.nudged': "We've told them. Now it's a bit of a wait.",
  'pending.nudgedToday': "We'd already told them today",
  'dup.rsvps': 'Who is going, everyone confirms again',
  'dup.availability': 'Availability, the poll starts empty',
  'dup.contribs': 'Who brings what, the list carries over unclaimed',
  'dup.guests': 'Guests, nobody drags their plus-ones along',
  'dup.failed': "Couldn't duplicate the event.",
  'event.noPlaceYet2': 'No place yet',
  'event.copyFailed': "Couldn't copy. Press and hold the link.",
  'event.toBin': 'It goes to the bin. 30 days to get it back.',
  'event.askedAdmin': "We've asked the club's admins",
  'event.cancelledNotice': 'Event cancelled. Everyone who was going has been told.',
  'event.binNoPhotos': "This event is in the bin, photos can't be added.",
  'event.onlyWentPhotos': 'Only people who went can add photos.',
  'event.askedToJoin': "You've asked to join. An organizer or admin will let you in soon.",
  'event.guestCanRsvp': "You can RSVP and bring something to this event even though you're not in the club.",
  'event.fixedTime': 'fixed the time',
  'event.join.anyone': 'Anyone with the link can get in.',
  'event.join.invite': 'Invite only.',
  'event.join.members': 'Club members only.',
  'event.withWaitlist': ', with a waitlist',
  'event.noWaitlist': ', with no waitlist',
  'poll.alive': 'The poll is live.',
  'poll.ph': 'What shall we play?',
  'poll.question': 'Question',
  'poll.anon': 'anonymous',
  'event.howPaid': 'How you get paid back',
  'event.payDetails': 'Payment details',
  'event.myDetails': 'my details',
  'event.claimed': "Claimed. The club is counting on you.",
  'contrib.added': 'Added to the bring list.',
  'contrib.updated': 'Contribution updated.',
  'contrib.whatNeeded': 'What is needed',
  'contrib.whatBring': "What you'll bring",
  'event.rollcall.failed': "Couldn't save the roll call.",
  'event.organization': 'the organizers',
  'money.expense.saved': 'Expense saved. The split has been updated.',
  'money.expense.failed': "Couldn't save the expense.",
  'inv.resent': 'Invitation resent',
  'form.grain.hint': 'Quick to mark. Enough for most plans.',
  'common.back2': 'Back',
  'common.more': 'More',
  'common.notSent': "Couldn't send.",
  'common.notUpdated': "Couldn't update.",
  'money.notRecorded': "Couldn't record the payment.",
  'ui.emoji.hint': 'Use the emoji on your keyboard',
  'ui.code.label': '6 digit code',
  'ui.code.expired': 'It expired. Ask for a new one.',
  'ui.crop.hint': 'Drag to move, slide to zoom',
  'app.description': 'Club events without the chaos: the date, the RSVPs, who brings what, the money.',
  'plate.snooze': 'Come back tomorrow',
  'admin.outbox.sent': 'sent',
  'admin.outbox.waiting': 'waiting on confirmation',
  'admin.outbox.queued': 'queued',
  'admin.outbox.logged': 'logged',
  'admin.tpl.approved': 'approved',
  'admin.tpl.rejected': 'rejected',
  'admin.tpl.paused': 'paused',
  'admin.tpl.disabled': 'disabled',
  'admin.outbox.failed': 'failed',
  'admin.noClub': 'Not in a club yet.',
  'admin.inClub': 'Already in a club.',
  'admin.moreWait': '{n} more waiting',
  'admin.moreWaitOne': '1 more waiting',
  'admin.tpl.review': 'under review',
  'admin.tpl.send': 'Send for review',
  'admin.tpl.resend': 'Send for review again',
  'inv.notFound': 'Invitation not found',
  'club.about.sent': 'Sent to the admins to approve.',
  'club.about.willApprove': 'An admin will approve your changes',
  'club.about.submit': 'Send for approval',
  'club.cat.new': 'New category',
  'club.cat.delete': 'Delete category',
  'club.cat.add': 'Add category',
  'club.about.editLink': 'edit the description and links',
  'club.underReview': 'under review',
  'club.cal.every': 'every event, in your calendar',
  'club.roster.recorded': 'Each one was recorded by whoever organized it, after the event.',
  'club.roster.fromRsvp': 'Some of it is counted from RSVPs: events that finished before the roll call existed.',
  'club.roster.allRsvp': 'Counted from RSVPs. Nobody took a roll call at those events, so it is an estimate.',
  'club.roster.none': 'no attendance yet',
  'club.roster.remove': 'Request removal',
  'club.cal.copyFailed': "Couldn't copy. Press and hold the link.",
  'club.cal.newLink': 'New link. The old one has stopped working.',
  'club.cal.changeFailed': "Couldn't change the link.",
  'club.invite.emailPh': 'name@email.com',
  'club.invite.note': 'Organizers invite members. Only an admin makes somebody an organizer or an admin.',
  'club.lastAdmin': "You're the last admin",
  'club.reinvited': 'You can be invited back later',
  'club.onlyMember': 'for its only member',
  'form.catNew': 'New category…',
  'form.askedAdmin': "We've asked the club's admins. In the meantime, the event is created anyway.",
  'form.grain.fine': 'More precise. The grid comes out twice as long.',
  'photos.uploadFailed': "Couldn't upload the photo.",
  'photos.removeFailed': "Couldn't remove the photo.",
  'event.binNoPhotos2': "This event is in the bin, photos can't be added.",
  'event.onlyWent2': 'Only people who went can add photos.',
  'event.saidYesOne': '1 person has said they are going',
  'event.saidYesMany': '{n} people have said they are going',
  'event.maybe': 'maybe',
  'event.askedJoin': "You've asked to join. An organizer or admin will let you in soon.",
  'event.guestJoinAsk': "You can RSVP and bring something here. Would you like the club's other events too?",
  'event.guestOk': "You can RSVP and bring something to this event even though you're not in the club.",
  'event.saidYouGo': "You're going",
  'event.saidMaybe': 'You said maybe',
  'event.saidNo': "You said you can't",
  'event.pending.none': 'No yes, no no, no availability.',
  'event.pending.reminded': 'The reminder has gone out. It only sends once.',
  'event.rsvp.saidComing': '{n} said they were coming',
  'pay.bank_account': 'Bank account',
  'pay.bank_code': 'CLABE',
  'pay.card': 'Card',
  'pay.cash': 'Cash',
  'pay.other': 'Other',
  'pay.add': 'Add a payment method',
  'pay.note': 'This is what somebody who owes you sees, so they know how to pay you. Only people who share a club with you can see it.',
  'account.wa.notAdded': 'not added',
  'account.wa.add': 'add',
  'common.change': 'change',
  'account.places.note': 'They show up as {yours} when you set the place for an event you organize, with its pin.',
  'push.meanwhile': 'Nothing is lost in the meantime: alerts keep reaching you by email and WhatsApp.',
  'push.incompatible': 'not supported',
  'club.change.about': 'About',
  'club.change.category_add': 'New category',
  'club.change.category_edit': 'Edit category',
  'club.change.category_delete': 'Delete category',
  'club.change.banner': 'Cover',
  'club.change.avatar': 'Club photo',
  'club.change.member_removal': 'Remove member',
  'event.capacityFor': 'room for {n}',
  'event.saidYes': '{n} people have said they are going.',
  'event.saidYesJustOne': '1 person has said they are going.',
  'search.upcomingOne': '{n} upcoming',
  'search.upcomingMany': '{n} upcoming',
  'admin.moreWaitLabel': '{n} more waiting',
  'club.forOneMember': ' for its only member',
  'club.forNMembers': ' for its {n} members',
  'form.askedAdminNoCat': "We've asked the club's admins. In the meantime the event is created without a category.",
  'inv.acceptJoins': 'Accepting joins you to «{club}».',
  'signin.noAccountEmailLong': 'If that email has no Hive account, nothing will arrive. Try your WhatsApp, or ask an organizer to invite you.',
  'club.roster.fromRsvp2': 'Some of it is counted from RSVPs: events that finished before roll call existed.',
  'club.roster.allRsvp2': 'Counted from RSVPs. Nobody took a roll call at those events, so it is whoever said they were going.',
  'rsvp.maybe': 'Maybe',
  'admin.noClubYet': 'Not in a club yet.',
  'admin.alreadyClub': 'Already in a club.',
  'admin.morePending': '· {n} more waiting, oldest first',
  'admin.morePendingOne': '· 1 more waiting, oldest first',
  'search.upcomingCount': '{n} upcoming',
  'search.upcomingCountOne': '1 upcoming',
  'money.saysPaid': '{from} says they paid {amount} to {to}',
  'event.andMore': ' and {n} more',
  'event.rollcall.cameOne': '1 said they were coming',
  'event.rollcall.cameMany': '{n} said they were coming',
  'event.rollcall.tapAbsent': "Tap whoever didn't make it, usually nobody.",
  'event.inviteOnlyNote': 'This event is invite only (or the link is wrong). Ask an organizer to invite you.',
  'cal.add': 'Add to your calendar',
  'cal.google': 'Google Calendar',
  'cal.other': 'Apple, Outlook and others',
  'roll.take': 'Take the roll call',
  'roll.quick': 'About fifteen seconds. Only the organizer sees it, and it can be corrected later.',
  'roll.fix': 'Correct',
  'roll.allCame': 'Everyone came',
  'roll.nobody': 'Nobody',
  'roll.saved': 'Roll call saved.',
  'claim.mine': "I'll take it",
  'claim.yes': "Yes, I'll bring it",
  'claim.openSpot': 'Open a spot (the next person moves up)',
  'claim.note': 'Once you claim it, the club is counting on you. Only an organizer can reassign it after that.',
  'dup.title': 'Duplicate this event',
  'dup.notice': 'Creating it tells the whole club straight away, by email and WhatsApp. There is no draft step and the notice cannot be pulled back.',
  'dup.weekNote': 'Members still pick the day inside that week. This only says where to look.',
  'event.cancelEvent': 'Cancel event',
  'event.deleteEvent': 'Delete event',
  'event.prev': 'Previous',
  'event.next': 'Next',
  'poll.new': 'New poll',
  'poll.create': 'Create poll',
  'poll.multi': 'several options',
  'poll.resultsAtClose': 'results when it closes',
  'money.expenses': 'Expenses',
  'money.balances': 'Balances',
  'money.saveExpense': 'Save expense',
  'money.youPaidNote': 'You paid it, so you are owed the total; it splits evenly between whoever you tick.',
  'club.theClub': 'the club',
  'common.seeAllF': 'See all',
  'event.fixRange': 'Fix this range',
  'event.reused': "This list carries over from last time. Nobody has claimed anything yet, and that's right: claim it again if you're bringing it.",
  'event.cancelledLong': 'This event was cancelled. RSVPs and the bring list are closed, everything else stays as history. Everyone has been told by email and WhatsApp.',
  'event.invite': 'Invite',
  'event.held': 'Event held',
  'event.closedBy': 'Closed by {name}',
  'money.paidBy': '· paid by {name}',
  'money.betweenOne': '{amount} between 1 person',
  'money.betweenMany': '{amount} between {n} people',
  'money.upDownNote': 'If the amount goes up, a new debt opens for the difference. If it goes down, the difference is owed back to whoever paid.',
  'photos.empty': 'No photos yet. Whatever you upload is seen by whoever was at the event.',
  'photos.add': 'Add',
  'event.pay': 'Pay',
  'event.goingLine': 'going {going} · not going {out}',
  'event.you': 'You',
  'line.nobodyAnswered': 'Nobody has answered',
  'line.youGo': "You're in",
  'line.youAndMore': "You're in, and {n} more",
  'line.nobodyYet': 'Nobody is going yet',
  'line.nobodyYetMaybe': 'Nobody is going yet, you said maybe',
  'line.nobodyYetYouOut': "Nobody is going yet, you either",
  'line.going': '{n} going',
  'line.goingMaybe': '{n} going, you said maybe',
  'line.goingYouOut': "{n} going, not you",
  'line.goingUnanswered': "{n} going, you haven't said",
  'club.noEventsYet': 'No events yet.',
  'time.never': 'never',
  'time.soon': 'soon',
  'time.today': 'today',
  'time.yesterday': 'yesterday',
  'time.daysAgo': '{n} days ago',
  'time.weekAgo': '1 week ago',
  'time.weeksAgo': '{n} weeks ago',
  'time.monthAgo': '1 month ago',
  'time.monthsAgo': '{n} months ago',
  'event.goingN': '{n} going',
  'event.ofCapacity': ' of {n}',
  'event.waitingN': ' · {n} waitlisted',
  'event.notGoingN': ' · {n} not going',
  'event.maybeN': ' · {n} maybe',
  'event.goingCount': '{n} going',
  'details.label': 'Details, organizers, calendar',
  'signin.tagline': 'Your club, organized.',
  'signin.welcome': "Welcome to the swarm. Let's find a date.",
  'signin.field': 'Your email or WhatsApp',
  'signin.hint': 'Either your email or your WhatsApp. Both get you a 6 digit code.',
  'signin.noPasswords': 'No passwords.',
  'signin.invited': 'Invited over WhatsApp? Use the link you were sent.',
  'signin.code': 'Your code',
  'signin.codeSent': 'We sent you a 6 digit code.',
  'signin.resend': 'Resend',
  'signin.resendLong': "Didn't arrive? Ask for another",
  'signin.sending': 'Sending…',
  'signin.helper.email': 'We will send a 6 digit code to that email.',
  'signin.helper.phone': 'We will send a 6 digit code to {display} on WhatsApp.',
  'signin.helper.short': 'A number gets the code on WhatsApp. Mexican numbers do not need the +52.',
  'signin.action.email': 'Send me the code by email',
  'signin.action.whatsapp': 'Send me the code on WhatsApp',

  // -- pending --------------------------------------------------------------
  'pending.title': "You're in the queue",
  'pending.body': "A Hive admin has to approve your account. We'll tell you the moment it's ready; we know you're here.",
  'pending.next': "An admin reviews new accounts. You're next.",
  'pending.buzz': 'Buzzing in the queue…',
  'pending.remind': 'Remind them',
}
